FirstClose/helm-charts

- charts/aspnet/Chart.yaml
- charts/aspnet/templates/deployment.yaml
- charts/fcone/Chart.yaml
- charts/fcone/templates/deployment.yaml
> TECH-372 Reverts ssl on aspnet and adds it to fcone

- charts/aspnet/Chart.yaml
- charts/aspnet/templates/service.yaml
> TECH-372 Add ssl to fcone service template

- charts/aspnet/Chart.yaml
- charts/aspnet/templates/service.yaml
- charts/fcone/Chart.yaml
- charts/fcone/templates/service.yaml
> Tech 372 add ssl fcone

- charts/fcone/Chart.yaml
- charts/fcone/templates/service.yaml
> Updates syntax on targetport for fcone service

- charts/fcone/Chart.yaml
- charts/fcone/templates/service.yaml
> TECH-233: Update service details

- charts/fcone/Chart.yaml
- charts/fcone/values.yaml
> TECH-232: Update service

- charts/kafka/Chart.yaml
- charts/kafka/templates/kafka.yml
Add kafkaExporter annotations
xxx
xxx 
xxx
xxx
xxx
xxx
[TECH-122]: https://firstclose.atlassian.net/browse/TECH-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-122: add kafkaExporter annotations

- charts/aspnet/Chart.yaml
- charts/aspnet/templates/deployment.yaml
> TECH-431: Integrate Host Alies

- charts/aspnet/Chart.yaml
- charts/aspnet/templates/deployment.yaml
- charts/fcone/Chart.yaml
- charts/fcone/templates/deployment.yaml
> TECH-431: Update FCOne helm template

- charts/devops/.helmignore
- charts/devops/Chart.yaml
- charts/devops/templates/NOTES.txt
- charts/devops/templates/_helpers.tpl
- charts/devops/templates/configMap.yaml
- charts/devops/templates/deployment.yaml
- charts/devops/templates/hpa.yaml
- charts/devops/templates/ingress.yaml
- charts/devops/templates/secrets.yaml
- charts/devops/templates/service.yaml
- charts/devops/templates/serviceaccount.yaml
- charts/devops/templates/tests/test-connection.yaml
- charts/devops/values.yaml
> TECH-447: Setup devops helm-chart

- charts/fcone/Chart.yaml
- charts/fcone/templates/service.yaml
TECH-449: Include session affinity on FCOne
xxx
xxx 
xxx
xxx
xxx
xxx
[TECH-449]: https://firstclose.atlassian.net/browse/TECH-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-449: Include session affinity on FCOne

- charts/devops/templates/deployment.yaml
- charts/devops/templates/service.yaml
- charts/devops/values.yaml
> added values to manifests

- charts/devops/templates/deployment.yaml
- charts/devops/templates/service.yaml
- charts/devops/values.yaml
> rever new values changes

- charts/nifi/Chart.yaml
> TECH-475: Bump Chart Version

- charts/limacharlie/values.yaml
> fix: use correct LimaCharlie sensor image"

- charts/kafka/Chart.yaml
- charts/kafka/values.yaml
> TECH-478: Upgrade Kafka to 4.8.1

- charts/kafka/Chart.yaml
> TECH-478: Update Kafka

- charts/kafka/Chart.yaml
> TECH-478: Upgrade kafka

- charts/nextjs/Chart.yaml
- charts/nextjs/templates/configMap.yaml
- charts/nextjs/templates/hpa.yaml
- charts/nextjs/templates/ingress.yaml
- charts/nextjs/templates/serviceaccount.yaml
xxx
xxx
xxx 
xxx
xxx
xxx
xxx
[TECH-609]: https://firstclose.atlassian.net/browse/TECH-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-609: fix syntax error in helm props

- charts/kafka/Chart.yaml
- charts/kafka/templates/KafkaNodePool.yml
- charts/kafka/templates/kafka.yml
- charts/kafka/values.yaml
- Refactor nodepools name
- upgrade patch version to chart
- removed zookeeper config from chart
xxx
xxx 
xxx
xxx
xxx
xxx
[TECH-634]: https://firstclose.atlassian.net/browse/TECH-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-634: remove zookeeper config from kafka chart

- charts/kafka/Chart.yaml
- charts/kafka/templates/KafkaNodePool.yml
xxx
xxx
xxx 
xxx
xxx
xxx
xxx
[TECH-620]: https://firstclose.atlassian.net/browse/TECH-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-620: upgrade minor version > complete removed of zookeeper

- charts/fcone/Chart.yaml
- charts/fcone/templates/ingress.yaml
- charts/fcone/values.yaml
> TECH-651: Enable multi ingress solution

- charts/fcone/Chart.yaml
- charts/fcone/templates/secrets.yaml
> TECH-651: Update secrets mount

- charts/fcone/Chart.yaml
- charts/fcone/templates/secrets.yaml
> TECH-651: Update to 1.0.21
